### ISSUE TITLE
how to access  i2b2 dataset

### ISSUE THREAD

**Issue by sunalbert** [Machine-Learning-for-Medical-Language/source-free-domain-adaptation#4]
Hi, I am a participant of source-free-domain-adaptation. When I apply for the access to the i2b2 2010 Challenge data fowllowing task instruction, the websites shows that **Registration is not open for Unstructured notes from the Research Patient Data Registry at Partners Healthcare at this time**. It seems that i2b2 2010 Challenge data could not be accessed through n2c2/DBMI Data Portal. 
Are there other ways to get these data?  Any suggestions for data access? Thanks.

**Comment by tmills** [comment]
I'm told that there is some temporary downtime but it should be back to normal this week.
